<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\Talk\Tests\php\Federation\Attachments;

use OCA\Talk\Federation\Attachments\ReceivedShareLookup;
use OCP\DB\QueryBuilder\IQueryBuilder;
use OCP\IDBConnection;
use OCP\Server;
use PHPUnit\Framework\Attributes\Group;
use Test\TestCase;

#[Group('DB')]
class ReceivedShareLookupTest extends TestCase {
	protected IDBConnection $db;
	/** @var list<int> */
	protected array $ids = [];

	public function setUp(): void {
		parent::setUp();
		$this->db = Server::get(IDBConnection::class);
	}

	public function tearDown(): void {
		$delete = $this->db->getQueryBuilder();
		$delete->delete('share_external')
			->where($delete->expr()->in('id', $delete->createNamedParameter($this->ids, IQueryBuilder::PARAM_INT_ARRAY)));
		$delete->executeStatement();
		parent::tearDown();
	}

	private function addReceivedShare(string $remote, string $remoteId, string $user, string $mountpoint, int $accepted): void {
		// share_external ids are snowflake ids generated by files_sharing, so pick our own
		$id = 9000000000000000000 + random_int(1, 999999999);
		$insert = $this->db->getQueryBuilder();
		$insert->insert('share_external')
			->values([
				'id' => $insert->createNamedParameter($id, IQueryBuilder::PARAM_INT),
				'share_type' => $insert->createNamedParameter(0, IQueryBuilder::PARAM_INT),
				'remote' => $insert->createNamedParameter($remote),
				'remote_id' => $insert->createNamedParameter($remoteId),
				'share_token' => $insert->createNamedParameter('token' . $remoteId),
				'name' => $insert->createNamedParameter(ltrim($mountpoint, '/')),
				'owner' => $insert->createNamedParameter('paul'),
				'user' => $insert->createNamedParameter($user),
				'mountpoint' => $insert->createNamedParameter($mountpoint),
				'mountpoint_hash' => $insert->createNamedParameter(md5($mountpoint)),
				'accepted' => $insert->createNamedParameter($accepted, IQueryBuilder::PARAM_INT),
			])
			->executeStatement();
		$this->ids[] = $id;
	}

	public function testFindAccepted(): void {
		$this->addReceivedShare('https://nc1.test/', '6', 'bill', '/Room-both-wqhg8fxn', 1);
		$this->addReceivedShare('https://nc3.test/', '6', 'bill', '/Other', 1);
		$this->addReceivedShare('https://nc1.test/', '7', 'bill', '/Pending', 0);

		$lookup = new ReceivedShareLookup($this->db);
		$this->assertSame('/Room-both-wqhg8fxn', $lookup->findAccepted('bill', 'https://nc1.test', '6'));
		$this->assertSame('/Other', $lookup->findAccepted('bill', 'nc3.test', '6'));
		$this->assertNull($lookup->findAccepted('bill', 'https://nc1.test', '7'), 'pending share');
		$this->assertNull($lookup->findAccepted('carol', 'https://nc1.test', '6'), 'other user');
	}
}
